name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        zig-version: ["0.13.0"]
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - zig-version: "0.12.1"
            os: ubuntu-latest
          - zig-version: "master"
            os: ubuntu-latest

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: ${{ matrix.zig-version }}

      - name: Build
        run: zig build ${{ matrix.os == 'windows-latest' && '-Dtarget=x86_64-windows-msvc' || '' }} --summary all